config/routes.rb
Rails.application.routes.draw do

  get '/', to:'home#index'
  get 'admin', to: 'admin/idiomas#index'

  namespace :admin do
    resources :home
    resources :idiomas
    resources :banners
    resources :trabajos
    resources :empresas
    resources :send_mail, only: [:edit, :create]

    get 'idiomas', to: 'idiomas#index'
  end
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end
  devise_for :users, :skip=>[:registrations]
  root 'home#index'

end

app/models/banner.rb
class Banner < ActiveRecord::Base
  # paperclip
  has_many :banner_texto

  has_attached_file :picture, styles: { large:"1256x578#", medium: "320x150#", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
  has_attached_file :picture, styles: { large:"445x500#", medium: "320x150#", thumb: "85x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
end

app/models/idioma.rb
class Idioma < ActiveRecord::Base
  has_one :texto
  def idiomas
    "#{id}.#{nombre}"
  end
end

app/models/trabajo.rb
class Trabajo < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/banners_controller.rb
class Admin::BannersController < AdminController
  before_action :set_banner, only: [:edit, :update, :destroy]
    def index
      @banners = Banner.all

    end
    def new
      @banner = Banner.new
      
    end
    def create
      @banner = Banner.create(params_banner)
      unless @banner.errors.any?
        redirect_to admin_banners_path, notice: "banner creado correctamente"
      else
        render :new
      end
    end
    def edit
      #code
    end
    def update
      @banner.update(params_banner)
      unless @banner.errors.any?
        redirect_to admin_banners_path, notice: "banner actulizado correctamente"
      else
        render :edit
      end
    end
    def destroy
      #code
    end

    private
    def set_banner
      @banner = Banner.find(params[:id])
    end
  def params_banner
    params.require(:banner).permit(:url_banner ,:picture, :titulo, :descripcion, :a_titulo, :a_descripcion)
  end
end

app/controllers/admin/empresas_controller.rb
class Admin::EmpresasController < AdminController
  before_action :set_empresa, only: [:edit, :update]
def edit
  @empresas = Empresa.all

end
def update
@empresa.update(params_empresa)
unless @empresa.errors.any?
  redirect_to edit_admin_empresa_path(1), notice: 'Empresa fue actulizado correctamente'
else
  render :edit
end
end
private
def set_empresa
  @empresa = Empresa.find(params[:id])
end
def params_empresa
  params.require(:empresa).permit(:id, :titulo, :descripcion, :picture)
end

end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController
layout "admin"
  def index
  
  end
end

app/controllers/admin/idiomas_controller.rb
class Admin::IdiomasController < AdminController
  before_action :set_idioma, only: [:edit, :update, :update_destroy]
  def index
    @idiomas = Idioma.all
  end
  def new
    @idioma = Idioma.new
  end
  def create
    @idioma = Idioma.create(params_idiomas)
    unless @idioma.errors.any?
      redirect_to admin_idiomas_path, notice: "el idioma #{@idioma.nombre} fue creado correctamente"
    else
      render :new
    end

  end
  def edit
    #code
  end
  def update
    @idioma.update(params_idiomas)
    unless @idioma.errors.any?
      redirect_to admin_idiomas_path, notice: "el idioma #{@idioma.nombre} fue actualizado"
    else
      render :edit
    end
  end
  def destroy
    #code
  end
  def update_destroy

    redirect_to admin_idiomas_path, notice: "el idioma #{@idioma.nombre} fue econtrado"
  end

  private
  def set_idioma

    @idioma = Idioma.find(params[:id])
  end
  def params_idiomas
    params.require(:idioma).permit(:nombre, :link)
  end
end

app/controllers/admin/send_mail_controller.rb
class Admin::SendMailController < ApplicationController
  def create
      begin
        AdminMailer.send_message(params[:'name-text'], params[:'asunto-text'],
        params[:'to-text'], params[:'message-text']).deliver_now

        @notify_message = "Email enviado con succeso"
        @notify_flag = "success"
      rescue
        @notify_message = "Error ao enviar o Email. intente otra vez.."
        @notify_flag = "error"
      end
      respond_to do |format|
        format.js
      end

    end
end

app/controllers/admin/trabajos_controller.rb
class Admin::TrabajosController < AdminController
before_action :set_trabajo, only: [:edit, :update, :destroy]
  def index
    @trabajos = Trabajo.all
  end
  def new
    @trabajo = Trabajo.new
  end
  def create
    @trabajo = Trabajo.create(params_trabajo)
    unless @trabajo.errors.any?
      redirect_to admin_trabajos_path, notice: 'creado correctamente'
    else
      render :new
    end

  end
  def edit
    #code
  end
  def update

    @trabajo.update(params_trabajo)
    unless @trabajo.errors.any?
      redirect_to admin_trabajos_path, notice: 'actualizado correctamente'
    else
      render :edit
    end
  end
  def destroy
    #code
  end
  private
  def set_trabajo
    @trabajo = Trabajo.find(params[:id])
  end
  def params_trabajo
    params.require(:trabajo).permit(:titulo, :descripcion, :icon, :animate)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  layout 'admin'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # Set Layout
  layout :layout_by_resource
  protected

  def layout_by_resource

    if devise_controller? && resource_name == :user
      "admin_devise"
    else
      "index"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'index'
  def index
    @idiomas = Idioma.all
    @banner = Banner.all
    @empresas = Empresa.all
    @hacemos = Trabajo.all
  end

end

app/helpers/admin/banners_helper.rb
module Admin::BannersHelper
end

app/helpers/admin/empresas_helper.rb
module Admin::EmpresasHelper
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/admin/idiomas_helper.rb
module Admin::IdiomasHelper
end

app/helpers/admin/send_mail_helper.rb
module Admin::SendMailHelper
end

app/helpers/admin/trabajos_helper.rb
module Admin::TrabajosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/banners/edit.html.erb
<%= render partial: "admin/banners/shared/form", locals: {action: "edit banner"}%>

app/views/admin/banners/index.html.erb
                <h1 class="page-header">Banner</h1>

                <%if notice%>
                <div class="alert alert-success alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <%=notice%>
                </div>
                <% end%>



                <!-- <div class="col-lg-6"> -->
                    <div class="panel panel-default">
                        <div class="panel-heading">
                          Listando Banner




                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>nombre</th>
                                            <th>titulo</th>
                                            <th>descripcion</th>
                                            <th></th>

                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                      <% @banners.each do |banner| %>
                                        <tr>
                                            <td><%= banner.id%></td>
                                            <td><%= banner.url_banner%></td>
                                            <td><%= banner.titulo%></td>
                                            <td><%= banner.descripcion%></td>
                                            <td><%= image_tag banner.picture.url(:thumb) %></td>

                                            <td style="width: 150px">
                                              <%=link_to edit_admin_banner_path(banner.id), class: "btn btn-primary btn-circle" do%>
                                            <i class="fa fa-edit"></i>
                                            <%end%>
                                              <%=link_to admin_banner_path(banner.id), class: "btn btn-danger btn-circle" do%>
                                            <i class="fa fa-minus"></i>
                                            <%end%>

                                            </td>

                                        </tr>
                                        <%end%>

                                    </tbody>
                                </table>
                            </div>
                            <!-- /.table-responsive -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                <!-- </div> -->

app/views/admin/banners/new.html.erb
<%= render partial: "admin/banners/shared/form", locals: {action: "Banner"} %>

app/views/admin/banners/shared/_form.html.erb
                <h1 class="page-header">Banner</h1>
                <% if @banner.errors.any? %>
                  <div class="alert alert-danger alert-dismissable">
                      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                      <ul>
                        <% @banner.errors.full_messages.each do |messages| %>
                        <li><%= messages%></li>
                        <% end %>
                      </ul>
                  </div>
                  <%end%>

                <!-- <div class="col-lg-6"> -->
                    <div class="panel panel-default">
                        <div class="panel-heading">

                          <%= action %>
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                          <div class="col-lg-6">

                            <%=form_for([:admin, @banner], html: { multipart: true }) do |f|%>
                            <div class="form-group">
                                <%=f.label :url_banner%><br>
                                <%= f.text_field :url_banner, class: "form-control"%>

                            </div>
                              <div class="form-group">
                                  <%=f.label :picture%><br>
                                  <%=f.file_field :picture, class:"btn btn-default"%>

                              </div>
                              <div class="form-group">
                                  <%=f.label :titulo%><br>
                                  <%= f.text_field :titulo, class: "form-control"%>
                              </div>
                              <div class="form-group">
                                  <%=f.label :animate_titulo%><br>
                                  <%= f.text_field :a_titulo, class: "form-control"%>
                              </div>
                              <div class="form-group">
                                    <%=f.label :descripcion%><br>
                                  <%= f.text_area :descripcion, class: "form-control"%>
                              </div>
                              <div class="form-group">
                                  <%=f.label :animate_descripcion%><br>
                                  <%= f.text_field :a_descripcion, class: "form-control"%>
                              </div>

                              <button type="submit" class="btn btn-default">Salvar</button>
                            <%end%>

                          </div>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                <!-- </div> -->

app/views/admin/empresas/edit.html.erb
<%= render partial: "admin/empresas/shared/form", locals: {action: "edit empresa"}%>

app/views/admin/home/index.html.erb
 <h1>home - index</h1>

app/views/admin/idiomas/edit.html.erb
<%= render partial: "admin/idiomas/shared/form", locals: {action: "editar que hacemos"} %>

app/views/admin/idiomas/index.html.erb
                <h1 class="page-header">IDIOMAS</h1>

                <%if notice%>
                <div class="alert alert-success alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <%=notice%>
                </div>
                <% end%>



                <!-- <div class="col-lg-6"> -->
                    <div class="panel panel-default">
                        <div class="panel-heading">
                          Listando Idiomas




                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Nombre</th>
                                            <th>Link</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                      <% @idiomas.each do |idioma| %>
                                        <tr>
                                            <td><%= idioma.id%></td>
                                            <td><%= idioma.nombre%></td>
                                            <td><%= idioma.link%></td>
                                            <td style="width: 150px">
                                              <%=link_to edit_admin_idioma_path(idioma.id), class: "btn btn-primary btn-circle" do%>
                                            <i class="fa fa-edit"></i>
                                            <%end%>
                                              <%=link_to admin_path(idioma.id), class: "btn btn-danger btn-circle" do%>
                                            <i class="fa fa-minus"></i>
                                            <%end%>

                                            </td>

                                        </tr>
                                        <%end%>

                                    </tbody>
                                </table>
                            </div>
                            <!-- /.table-responsive -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                <!-- </div> -->

app/views/admin/idiomas/new.html.erb
<%= render partial: "admin/idiomas/shared/form", locals: {action: "Nuevos que hacemos"} %>

app/views/home/index.html.erb
<h1>home</h1>