config/routes.rb
Rails.application.routes.draw do

  get '/', to:'home#index'
  get 'admin', to: 'admin/idiomas#index'

  namespace :admin do
    resources :home
    resources :idiomas
    resources :banners
    resources :trabajos
    resources :empresas
    resources :send_mail, only: [:edit, :create]

    get 'idiomas', to: 'idiomas#index'
  end
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
  end
  devise_for :users, :skip=>[:registrations]
  root 'home#index'

end

app/models/banner.rb
class Banner < ActiveRecord::Base
  # paperclip
  has_many :banner_texto

  has_attached_file :picture, styles: { large:"1256x578#", medium: "320x150#", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
  has_attached_file :picture, styles: { large:"445x500#", medium: "320x150#", thumb: "85x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
end

app/models/idioma.rb
class Idioma < ActiveRecord::Base
  has_one :texto
  def idiomas
    "#{id}.#{nombre}"
  end
end

app/models/trabajo.rb
class Trabajo < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/banners_controller.rb
class Admin::BannersController < AdminController
  before_action :set_banner, only: [:edit, :update, :destroy]
    def index
      @banners = Banner.all

    end
    def new
      @banner = Banner.new
      
    end
    def create
      @banner = Banner.create(params_banner)
      unless @banner.errors.any?
        redirect_to admin_banners_path, notice: "banner creado correctamente"
      else
        render :new
      end
    end
    def edit
      #code
    end
    def update
      @banner.update(params_banner)
      unless @banner.errors.any?
        redirect_to admin_banners_path, notice: "banner actulizado correctamente"
      else
        render :edit
      end
    end
    def destroy
      #code
    end

    private
    def set_banner
      @banner = Banner.find(params[:id])
    end
  def params_banner
    params.require(:banner).permit(:url_banner ,:picture, :titulo, :descripcion, :a_titulo, :a_descripcion)
  end
end

app/controllers/admin/empresas_controller.rb
class Admin::EmpresasController < AdminController
  before_action :set_empresa, only: [:edit, :update]
def edit
  @empresas = Empresa.all

end
def update
@empresa.update(params_empresa)
unless @empresa.errors.any?
  redirect_to edit_admin_empresa_path(1), notice: 'Empresa fue actulizado correctamente'
else
  render :edit
end
end
private
def set_empresa
  @empresa = Empresa.find(params[:id])
end
def params_empresa
  params.require(:empresa).permit(:id, :titulo, :descripcion, :picture)
end

end

app/controllers/admin/home_controller.rb
class Admin::HomeController < ApplicationController
layout "admin"
  def index
  
  end
end

app/controllers/admin/idiomas_controller.rb
class Admin::IdiomasController < AdminController
  before_action :set_idioma, only: [:edit, :update, :update_destroy]
  def index
    @idiomas = Idioma.all
  end
  def new
    @idioma = Idioma.new
  end
  def create
    @idioma = Idioma.create(params_idiomas)
    unless @idioma.errors.any?
      redirect_to admin_idiomas_path, notice: "el idioma #{@idioma.nombre} fue creado correctamente"
    else
      render :new
    end

  end
  def edit
    #code
  end
  def update
    @idioma.update(params_idiomas)
    unless @idioma.errors.any?
      redirect_to admin_idiomas_path, notice: "el idioma #{@idioma.nombre} fue actualizado"
    else
      render :edit
    end
  end
  def destroy
    #code
  end
  def update_destroy

    redirect_to admin_idiomas_path, notice: "el idioma #{@idioma.nombre} fue econtrado"
  end

  private
  def set_idioma

    @idioma = Idioma.find(params[:id])
  end
  def params_idiomas
    params.require(:idioma).permit(:nombre, :link)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  layout 'admin'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  # Set Layout
  layout :layout_by_resource
  protected

  def layout_by_resource

    if devise_controller? && resource_name == :user
      "admin_devise"
    else
      "index"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'index'
  def index
    @idiomas = Idioma.all
    @banner = Banner.all
    @empresas = Empresa.all
    @hacemos = Trabajo.all
  end

end

app/helpers/admin/banners_helper.rb
module Admin::BannersHelper
end

app/helpers/admin/empresas_helper.rb
module Admin::EmpresasHelper
end

app/helpers/admin/home_helper.rb
module Admin::HomeHelper
end

app/helpers/admin/idiomas_helper.rb
module Admin::IdiomasHelper
end

app/helpers/admin/send_mail_helper.rb
module Admin::SendMailHelper
end

app/helpers/admin/trabajos_helper.rb
module Admin::TrabajosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/sections/edit.html.erb
<%= render partial: "admin/sections/shared/form", locals: {action: "editar section"} %>

app/views/admin/sections/index.html.erb
                <h1 class="page-header">SECTION</h1>

                <%if notice%>
                <div class="alert alert-success alert-dismissable">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <%=notice%>
                </div>
                <% end%>



                <!-- <div class="col-lg-6"> -->
                    <div class="panel panel-default">
                        <div class="panel-heading">
                          Listando section
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>Nombre</th>
                                            <th>Descripcion</th>
                                            <th>menu</th>
                                            <th>contacto</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                      <% @section.each do |section| %>
                                        <tr>
                                            <td><%= section.id%></td>
                                            <td><%= section.nombre%></td>
                                            <td><%= section.descripcion%></td>
                                            <td><%= section.section.menu%></td>
                                            <td><%= section.section.contacto%></td>
                                            <td style="width: 150px">
                                              <%=link_to edit_admin_section_path(section.id), class: "btn btn-primary btn-circle" do%>
                                            <i class="fa fa-edit"></i>
                                            <%end%>
                                              <%=link_to admin_section_path(section.id), class: "btn btn-danger btn-circle" do%>
                                            <i class="fa fa-minus"></i>
                                            <%end%>

                                            </td>

                                        </tr>
                                        <%end%>

                                    </tbody>
                                </table>
                            </div>
                            <!-- /.table-responsive -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                <!-- </div> -->

app/views/admin/sections/new.html.erb
<%= render partial: "admin/sections/shared/form", locals: {action: "Nueva section"} %>

app/views/admin/sections/shared/_form.html.erb
                  <h1 class="page-header">Section</h1>
                  <% if @textos.errors.any? %>
                    <div class="alert alert-danger alert-dismissable">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <ul>
                          <% @textos.errors.full_messages.each do |messages| %>
                          <li><%= messages%></li>
                          <% end %>
                        </ul>
                    </div>
                    <%end%>

                  <!-- <div class="col-lg-6"> -->
                      <div class="panel panel-default">
                          <div class="panel-heading">

                            <%= action %>
                          </div>
                          <!-- /.panel-heading -->
                          <div class="panel-body">
                            <div class="col-lg-6">

                              <%=form_for([:admin, @textos]) do |f|%>
                                <div class="form-group">
                                    <label>contacto</label>
                                    <%= f.text_field :menu, class: "form-control"%>
                                </div>
                                <div class="form-group">
                                    <label>contacto</label>
                                    <%= f.text_field :contacto, class: "form-control"%>
                                </div>

                                <%= f.fields_for :texto do |s| %>
                                <div class="field">
                                  <%= f.label :street %><br>
                                  <%= s.text_field :street %>
                                </div>
                                <div class="field">
                                  <%= f.label :city %><br>
                                  <%= s.text_field :city %>
                                </div>
                                <div class="field">
                                  <%= f.label :state %><br>
                                  <%= s.text_field :state %>
                                </div>
                              <% end %>

                                <button type="submit" class="btn btn-default">Salvar</button>
                              <%end%>


                            </div>
                          </div>
                          <!-- /.panel-body -->
                      </div>
                      <!-- /.panel -->
                  <!-- </div> -->

app/views/layouts/backoffice_shared/_navigation.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="index.html">Wigo</a>
    </div>
    <!-- /.navbar-header -->

    <ul class="nav navbar-top-links navbar-right">
        <li></li>
        <!-- /.dropdown -->
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li>
                  <%= link_to  destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out fa-fw"></i> Logout
                  <% end %>


                </li>
            </ul>
            <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
    </ul>
    <!-- /.navbar-top-links -->

    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">
                <li class="sidebar-search">
                    <div class="input-group custom-search-form">
                        <input type="text" class="form-control" placeholder="Search...">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <i class="fa fa-search"></i>
                            </button>
                        </span>
                    </div>
                    <!-- /input-group -->
                </li>
                <li>
                    <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Idiomas<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                          <%= link_to admin_idiomas_path do%>
                          <i class="fa fa-dashboard fa-fw"></i> lista
                          <% end%>
                          </li>
                        <li>
                          <%= link_to new_admin_idioma_path do%>
                          <i class="fa fa-dashboard fa-fw"></i> Nuevo
                          <% end%>

                        </li>
                    </ul>
                    <!-- /.nav-second-level -->
                </li>
                <li>
                    <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Banner<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                          <%= link_to  admin_banners_path do%>
                          <i class="fa fa-dashboard fa-fw"></i> lista
                          <% end%>
                          </li>
                        <li>
                          <%= link_to new_admin_banner_path do%>
                          <i class="fa fa-dashboard fa-fw"></i> Nuevo
                          <% end%>

                        </li>
                    </ul>
                    <!-- /.nav-second-level -->
                </li>
                <li>
                    <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Empresa<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                          <%= link_to edit_admin_empresa_path(1) do%>
                          <i class="fa fa-dashboard fa-fw"></i> lista
                          <% end%>
                          </li>

                    </ul>
                    <!-- /.nav-second-level -->
                </li>
                <li>
                    <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Que hacemos<span class="fa arrow"></span></a>
                    <ul class="nav nav-second-level">
                        <li>
                          <%= link_to  admin_trabajos_path do%>
                          <i class="fa fa-dashboard fa-fw"></i> lista
                          <% end%>
                          </li>
                        <li>
                          <%= link_to new_admin_trabajo_path do%>
                          <i class="fa fa-dashboard fa-fw"></i> Nuevo
                          <% end%>

                        </li>
                    </ul>
                    <!-- /.nav-second-level -->
                </li>




            </ul>
        </div>
        <!-- /.sidebar-collapse -->
    </div>
    <!-- /.navbar-static-side -->
</nav>